name: ttest
favicon: null
layout_spectrum: 0.74743
typography_spectrum: 0.30306
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#45c3b8'
    - '#000000'
    - '#ffffff'
    - '#3a847b'
    - '#aaaaaa'
  brandStrength: 0.871375307906419
  lightness: 0.7107516236137599
  saturation: 0.5791912095155567
  rhythmicContrast: 0.5151410731486976
purpose: []
